### ISSUE TITLE
interfaces fails to find VLAN devices

### ISSUE THREAD

**Issue by sangdrax8** [puzzle/puzzle.opnsense#125]
**Describe the bug**
I am trying to get the interfaces_assignments module to assign a vlan interface, and it gives the error  Device was not found on OPNsense Instance!

**To Reproduce**
Set the device to a vlan interface
```
- name: assign interfaces
  puzzle.opnsense.interfaces_assignments:
    identifier: "opt3"
    device: "vlan0.310"
    description: "IOT"
```
In the GUI, it is identified correctly, see the below screenshot.  When I use a different interface and fill in these fields, it works just fine for them.

**Expected behavior**
Configure the interface

**Screenshots**
![image](https://github.com/puzzle/puzzle.opnsense/assets/6662727/eddd1f6c-0a4c-4ed7-99f6-2192d1a3d755)

**Environment**
 - OS: puzzle.opnsense with molecule
 - ansible 2.16

**Additional context**
