### ISSUE TITLE
Issues with system_access_users module

### ISSUE THREAD

**Issue by GBBx** [puzzle/puzzle.opnsense#159]
**Describe the bug**
1. Inconsistent behaviour when creating a user.
I try to create a user using the system_access_users module in a role.
Task in the role:
```
- name: "create/remove test user"
  puzzle.opnsense.system_access_users:
    username: "joe"
    password: "password"
    state: "present"
    authorizedkeys: "......."
```

When I run the playbook with this role I get:
```
FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_puzzle.opnsense.system_access_users_payload_zrt8cd4y/ansible_puzzle.opnsense.system_access_users_payload.zip/ansible_collections/puzzle/opnsense/plugins/modules/system_access_users.py\", line 261, in <module>\n  File \"/tmp/ansible_puzzle.opnsense.system_access_users_payload_zrt8cd4y/ansible_puzzle.opnsense.system_access_users_payload.zip/ansible_collections/puzzle/opnsense/plugins/modules/system_access_users.py\", line 227, in main\n  File \"/tmp/ansible_puzzle.opnsense.system_access_users_payload_zrt8cd4y/ansible_puzzle.opnsense.system_access_users_payload.zip/ansible_collections/puzzle/opnsense/plugins/module_utils/config_utils.py\", line 167, in __exit__\nRuntimeError: Config has changed. Cannot exit without saving.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Interestingly, the user is there in the UI. If I delete the user and run the playbook again, there is no issue:
```
TASK [opnsense_user : create/remove test user] *****************************************************************************************************************************************************************************
--- before
+++ after
@@ -2,6 +2,6 @@
     "system": "\n    ",
     "system/maximumtableentries": "",
     "system/nextgid": "2000",
-    "system/nextuid": "2007",
+    "system/nextuid": "2008",
     "system/user": "\n      "
 }
```

2. the user cannot be removed by Ansible.
task in the role:
```
- name: "remove test user"
  puzzle.opnsense.system_access_users:
    username: "joe"
    state: absent
```

error:
```
FAILED! => {"changed": false, "msg": "missing required arguments: password"}
```

**Expected behavior**
I should be able to create or delete a user without having to run the playbook twice.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Sequoia
 - Version [e.g. 22] 15.0.1

**Additional context**
Target: OPNsense 24.7.6

**Comment by KiLLuuuhh** [comment]
Hello @GBBx,

Sorry for the late response; we've been quite busy automating our own network.

I was able to test the behavior you described on a 24.7.6 instance.

Test Task:
```
---
- name: converge
  hosts: all
  become: true
  tasks:
    - name: "test"
      ansible.builtin.debug:
        msg: "test"

    - name: "create test user"
      puzzle.opnsense.system_access_users:
        username: "joe"
        password: "password"
        full_name: "[ ANSIBLE ]"
        authorizedkeys: "test_authorized_key"

    - name: "remove test user"
      puzzle.opnsense.system_access_users:
        username: "joe"
        password: "password"
        state: absent
        full_name: "[ ANSIBLE ]"
        authorizedkeys: "test_authorized_key"
````
I was able to create the user without issues. However, I also encountered a bug when attempting to remove the user, which I have identified and will address with a Pull Request shortly.

Result:
```
TASK [create test user] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [24.7]

TASK [remove test user] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [24.7]
```

Do you have SSH access to the OPNsense instance? It would be helpful to see how the XML looks after the first run.

Could you send me the config snipped of your "joe" user like:

```
<user>
  <authorizedkeys>dGVzdF9hdXRob3JpemVkX2tleQ==</authorizedkeys>
  <expires/>
  <ipsecpsk/>
  <otp_seed/>
  <scope>user</scope>
  <name>joe</name>
  <password>$2y$11$GVGBe7B0XShgf/G5C0y9OOT6sJA6zgmNVryFc.hILE8MemRL0sYIi</password>
  <descr>[ ANSIBLE ]</descr>
  <full_name>[ ANSIBLE ]</full_name>
  <uid>2027</uid>
</user>
```
If you have any question, please let me know.
