### ISSUE TITLE
Module Request: system_settings_logging

### ISSUE THREAD

**Issue by rekup** [puzzle/puzzle.opnsense#52]
### Module Description

This module can be used to configure the settings available in the ui under `System` -> `Settings` -> `Logging`

![image](https://github.com/puzzle/puzzle.opnsense/assets/46689442/10296792-f6c4-4a60-b93f-8603db827900)

### Minimum Viable Product (MVP)

```yaml
module: system_settings_logging
short_description: Configure logging settings
description:
  - Module to configure system logging
options:
  preserve_logs:
    description: "Number of logs to preserve. By default 31 logs are preserved. When no max filesize is offered or the logs are smaller than the the size requested, this equals the number of days."
    type: int
    required: false
  max_log_filesize_mb:
    description: "Maximum filesize per log file, when set and a logfile exceeds the amount specified, it will be rotated."
    type: int
    required: false
```

### Examples

```yaml
---
- name: Set the number of logs to preserve to 10
  puzzle.opnsense.system_settings_logging:
    preserve_logs: 10
```

```yaml
---
- name: Set max log filesize to 5MB
  puzzle.opnsense.system_settings_logging:
    max_log_filesize_mb: 5
```
