### ISSUE TITLE
Module Request: services_dhcpv4

### ISSUE THREAD

**Issue by ombre8** [puzzle/puzzle.opnsense#58]
### Module Description

This module can be used to configure the settings available in the ui under `Services` -> `DHCPv4` -> `[$interfacename]`

![2024-03-21-134559_2105x1200_scrot](https://github.com/puzzle/puzzle.opnsense/assets/2480918/2439a208-0c82-4b9a-b817-6257a12ff96d)

### Minimum Viable Product (MVP)

```yaml
module: services_dhcpv4
short_description: Configure DHCP server for specific Interface.
description:
  - Module to configure general system settings
options:
  interface:
    description: "The Interface the DHCP server should be configured on"
    type: str
    required: true
  enable:
    description: Wheter the Server is enabled or not
    type: bool
    default: true
    required: false
  range_from:
    description: Start of the IP Pool
    type: str
    required: false
  range_to:
    description: End of the IP Pool
    type: str
    required: false
```

### Examples

```yaml
---
- name: Enable DHCP Server on LAN interface
  puzzle.opnsense.services_dhcpv4:
    interface: LAN

- name: Enable DHCP Server on guestwifi interface
  puzzle.opnsense.services_dhcpv4:
    interface: guestwifi
    enable: true
    range_from: 192.168.10.100
    range_to: 192.168.10.254
```

### Additional Notes (Optional)

* Starting with Opnsense 24.1 there are 2 DHCP Servers ISC (old) and Kea (new), what's described above references the old ISC Server
