### ISSUE TITLE
Module Request: interface assignments module

### ISSUE THREAD

**Issue by cfasnacht** [puzzle/puzzle.opnsense#59]
### Module Description

This module can be used to assign interfaces to network ports and network IDs to new interfaces.
In the Web GUI it can be found under: => `Interfaces` => `Assignments`

![opnsense_ass_int](https://github.com/puzzle/puzzle.opnsense/assets/5371784/d96387f9-e85b-4849-9cc6-83a7d8a9a322)

### Minimum Viable Product (MVP)

```yaml
module: interfaces_assignments
description:
  - Module to assign interfaces to network ports and interface IDs to new interfaces
options:
  id:
    description: interface ID
    type: str
    required: true
  network_port:
    description: Network port name
    type: str
    required: true
```

### Examples

```yaml
- name: Assign interface
  puzzle.opnsense.interfaces_assignments
    id: VAGRANT
    network_port: em4
    
- name: Assign interface ID
  puzzle.opnsense.interfaces_assignments
    id: mynewid
    network_port: em4
```
